version: '3'
services:
  worker:
    command:
      - /config/worker_with_env_vars.jsonnet

  pants:
    volumes:
      - ./:/code
      - ./pants.2_15_2_environments.toml:/code/pants.toml
      - pants_cache:/root/.cache
